name: Publish Python ğŸ distribution ğŸ“¦ to PyPI

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+\.?[0-9]?'

jobs:
  build:
    name: Build distribution ğŸ“¦
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Python package
        uses: ./.github/actions/build-python-package
        with:
          upload-artifact: true
          artifact-name: python-package-distributions-pypi

  publish-to-pypi:
    name: >-
      Publish Python ğŸ distribution ğŸ“¦ to PyPI
    if: ${{ github.repository == 'containers/podman-py' }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/podman
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v5
        with:
          name: python-package-distributions-pypi
          path: dist/
      - name: Publish distribution ğŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
